kind: Namespace
apiVersion: v1
metadata:
  name: omni-system

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: omni-config
  namespace: omni-system
data:
  OMNI_INFLUX_URL: "<your-url-here>"
  OMNI_INFLUX_TOKEN: "<your-token-here>"
  OMNI_INFLUX_BUCKET: "<your-bucket-here>"
  OMNI_INFLUX_ORG: "<your-organization-here>"
  OMNI_DATA_RATE_SECONDS: "5"

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: omni-metrics
  namespace: omni-system
spec:
  selector:
    matchLabels:
      app: omni-monitor
  template:
    metadata:
      labels:
        app: omni-monitor
    spec:
      volumes:
      - name: rootfs
        hostPath:
          path: /proc
      containers:
      - name: omni
        image: mattogodoy/omni:arm
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: omni-config
        env:
        - name: OMNI_HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: OMNI_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        volumeMounts:
        - name: rootfs
          mountPath: /rootfs/proc
          readOnly: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
